[package]
name = "vanityed25519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ssh-key = { version = "0.6.0-rc.2", default-features = false, features = ["alloc", "ed25519"] }
